language: java
jdk:
  - oraclejdk11

cache:
    directories:
     - $HOME/.m2/repository

jobs:
  include:
    - script: mvn clean verify

jobs:
  include:
    if: branch = develop
    script:
      - echo "$passwordDocker" | docker login -u "$usernameDocker" --password-stdin
      - docker build -t travis-db ./sample-application-db-changelog-job
      - docker tag travis-db $usernameDocker/travis-db # rename
      - docker push $usernameDocker/travis-db

      - docker build -t travis-app ./sample-application-http-api-server
      - docker tag travis-app $usernameDocker/travis-app # rename
      - docker push $usernameDocker/travis-app